class TblTokens:
    TABLE = "invite_tokens"
    ID = "id"
    TOKEN_STRING = "token_string"
    ADMIN_ID = "admin_id"
    CREATED_BY = "admin_id"  # backward compat alias
    CREATED_AT = "created_at"
    IS_USED = "is_used"
    USED_BY_ID = "used_by_telegram_id"
    USED_BY_USER = "used_by_username"  # snapshot at activation time
    TOKEN_TYPE = "token_type"
    CAPTION = "caption"
    IS_REVOKED = "is_revoked"
    SENT_TO = "sent_to"

class TblUsers:
    TABLE = "authorized_users"
    ID = "telegram_id"
    TOKEN_ID = "token_id"
    ADMIN_ID = "admin_id"
    USERNAME = "username"
    ACTIVATED_AT = "activated_at"
    CREATED_AT = "created_at"
    IS_BANNED = "is_banned"

class TblBotSettings:
    TABLE = "bot_settings"
    ID = "id"
    ADMIN_ID = "admin_id"
    CREATED_BY = "admin_id"  # backward compat alias
    STRICT_MODE = "strict_knowledge_mode"
    TEMPERATURE = "temperature"
    MAINTENANCE_MODE = "maintenance_mode"
    UPDATED_AT = "updated_at"

class TblChat:
    TABLE = "chat_analytics"
    ID = "id"
    TELEGRAM_ID = "telegram_id"
    USER_QUERY = "user_query"
    BOT_RESPONSE = "bot_response"
    ADMIN_ID = "admin_id"
    MODE = "mode"
    CREATED_AT = "created_at"

class TblFiles:
    TABLE = "ingested_files"
    ID = "id"
    FILENAME = "filename"
    UPLOADED_BY_ID = "uploaded_by_telegram_id"
    CREATED_AT = "created_at"
    ADMIN_ID = "admin_id"
    CREATED_BY = "admin_id"  # backward compat alias
    CATEGORY = "category"
    VECTOR_TEXT_COUNT = "vector_text_count"
    CONDENSATION_STATUS = "condensation_status"
    VECTOR_CHUNK_COUNT = "vector_chunk_count"
    CONDENSATION_COMPLETED_AT = "condensation_completed_at"

class TblUserStates:
    TABLE = "user_states"
    ID = "id"
    TELEGRAM_ID = "telegram_id"
    CURRENT_MODE = "current_mode"
    CURRENT_STEP = "current_step"
    METADATA = "metadata"
    UPDATED_AT = "updated_at"
    EXTRACTED_CONSTRAINTS = "extracted_constraints"
    CONSTRAINT_VERSION = "constraint_extraction_version"
    CONSTRAINTS_UPDATED_AT = "constraints_updated_at"

class TblOnboarding:
    TABLE = "onboarding_leads"
    ID = "id"
    TELEGRAM_ID = "telegram_id"
    FULL_NAME = "full_name"
    PHONE_NUMBER = "phone_number"
    EXPERIENCE_LEVEL = "experience_level"
    GOAL = "goal"
    CREATED_AT = "created_at"
    ROLE = "role"
    PASSION = "passion"
    TOKEN_ID = "token_id"
    ADMIN_ID = "admin_id" 
    TRAINING_STATUS = "training_status"

class TblTests:
    TABLE = "test_results"
    ID = "id"
    TELEGRAM_ID = "telegram_id"
    TOKEN_ID = "token_id"
    CATEGORY = "category"
    QA_DATA = "qa_data"
    SCORE = "score"
    TOTAL_QUESTIONS = "total_questions"
    REMARKS = "remarks"
    CREATED_AT = "created_at"
    ADMIN_ID = "admin_id"

# --- PHASE 2 TABLES ---

class TblCondensedCards:
    TABLE = "condensed_knowledge_cards"
    ID = "id"
    FILE_ID = "file_id"
    ADMIN_ID = "admin_id"
    CARD_JSON = "card_json"
    CARD_SIZE_BYTES = "card_size_bytes"
    ORIGINAL_SIZE_BYTES = "original_size_bytes"
    ORIGINAL_CHUNK_COUNT = "original_chunk_count"
    CONDENSED_CHUNK_COUNT = "condensed_chunk_count"
    PROCESSING_TIME = "processing_time_seconds"
    EXTRACTION_CALLS = "extraction_calls"
    REDUCTION_CALLS = "reduction_calls"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"

class TblAsymmetricAnchors:
    TABLE = "asymmetric_anchors"
    ID = "id"
    CARD_ID = "card_id"
    ADMIN_ID = "admin_id"
    QUERY_ANCHOR = "query_anchor"
    DOCUMENT_ANCHOR = "document_anchor"
    QUERY_EMBEDDING_ID = "query_embedding_id"
    DOCUMENT_EMBEDDING_ID = "document_embedding_id"
    RELEVANCE_SCORE = "relevance_score"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"

class TblKnowledgeCardChunks:
    TABLE = "knowledge_card_chunks"
    ID = "id"
    CARD_ID = "card_id"
    CHUNK_ID = "chunk_id"
    ORIGINAL_CHUNK_INDEX = "original_chunk_index"
    CHUNK_CONTENT = "chunk_content"
    CHUNK_CATEGORY = "chunk_category"
    CREATED_AT = "created_at"

class TblCondensationLogs:
    TABLE = "condensation_logs"
    ID = "id"
    ADMIN_ID = "admin_id"
    FILE_ID = "file_id"
    STAGE = "stage"
    STATUS = "status"
    TOKENS_USED = "tokens_used"
    COST_ESTIMATE = "cost_estimate"
    DURATION_SECONDS = "duration_seconds"
    ERROR_MESSAGE = "error_message"
    STARTED_AT = "started_at"
    COMPLETED_AT = "completed_at"

class TblCondensationMetrics:
    TABLE = "condensation_metrics"
    ID = "id"
    ADMIN_ID = "admin_id"
    METRIC_TYPE = "metric_type"
    METRIC_VALUE = "metric_value"
    FILE_ID = "file_id"
    MEASURED_AT = "measured_at"

class TblEmbeddingMetrics:
    TABLE = "embedding_metrics"
    ID = "id"
    ADMIN_ID = "admin_id"
    METRIC_TYPE = "metric_type"
    METRIC_VALUE = "metric_value"
    MEASURED_AT = "measured_at"
    FILE_ID = "file_id"
    QUERY_TYPE = "query_type"

class TblEmbeddings:
    TABLE = "embeddings"
    ID = "id"
    CHUNK_ID = "chunk_id"
    ADMIN_ID = "admin_id"
    VECTOR = "vector"
    EMBEDDING_MODEL = "embedding_model"
    SOURCE_TEXT = "source_text"
    CREATED_AT = "created_at"
    EMBEDDING_TYPE = "embedding_type"
    ANCHOR_TEXT = "anchor_text"
    CREATED_FROM_CHUNK_ID = "created_from_chunk_id"
    IS_PRIMARY = "is_primary"

class TblFileChunks:
    TABLE = "file_chunks"
    ID = "id"
    FILE_ID = "file_id"
    CHUNK_INDEX = "chunk_index"
    CONTENT = "content"
    CONTENT_HASH = "content_hash"
    ADMIN_ID = "admin_id"
    CONTENT_TYPE = "content_type"
    RELEVANCE_CATEGORY = "relevance_category"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
